### ISSUE TITLE
Deploying wipes custom domain

### ISSUE THREAD

**Issue by cyberwombat** [center-key/node-slate#11]
Each time I deploy it erases the Custom domain option of GH pages.

**Comment by pilafmon** [comment]
Do you mean your `CNAME` file gets deleted?  If so, what is the original path of the file and what is the expected result that would work for you project?

**Comment by cyberwombat** [comment]
Well that's the thing. I set the cname from the GH dashboard which creates the file which then gets deleted on deploys.  Should I place that CNAME file somewhere in my local folder to be deployed alongside the generated gh pages?

**Comment by cyberwombat** [comment]
#12

**Comment by pilafmon** [comment]
The `docs` folder with the `CNAME` file is for the sample `Kittn API` rather than the `node-slate` target output.

Adding some kind of new feature to help publish to a custom domain could be a valuable enhancement.  If anyone wants that feature, it's probably best to open a new issue detailing the enhancement.
