### ISSUE TITLE
Documentation on the index.yml file?

### ISSUE THREAD

**Issue by Fluffy9** [center-key/node-slate#23]
I want to build all the files in the include folder but it seems as if only the ones listed in the includes section of the index.yml folder are being used. How do I use all the files in the includes folder and subdirectories of it instead? It's too many to go through and list one by one. Can you provide documentation on what settings are available in general?

**Comment by pilafmon** [comment]
It's not clear how that could work because the documentation builder would have no way to know the desired order of the `.md` files.

However, it's pretty easy to get a list of files alphabetically from the command line.

Here's an example based on the default files in the **source/includes** folder:

```shell
% ls source/includes | sort | sed -e "s/[.]md//" -e "s/^/   - /"
   - _errors
   - main
```

Then you just paste the output into the `includes:` section of the **index.yml** file.

Alphabetical probably makes no sense unless you prefix the `.md` filenames with something sortable like a chapter number.  For example you could have the files: **chap01-overview.md**, **chap02-auth.md**, and **chap03-errors.md**

Then, the output would look something like:

```shell
% ls source/includes | sort | sed -e "s/[.]md//" -e "s/^/   - /"
   - chap01-overview
   - chap02-auth
   - chap03-errors
```

That way your chapters would be in the correct order.
